// src/components/Title.tsx
import { pick } from 'lodash'

// default props for Title component
export const defaultProps = {
  text: 'Hello World',
  fontSize: '30px'
}

// array that contains style props
export const stylePropsArr = ['fontSize']

const Title = (props: any, context: any) => {
  const mergeProps = { ...defaultProps, ...props }
  const styleProps = pick(mergeProps, stylePropsArr)
  console.log(mergeProps)
  console.log(styleProps)
  return (
    <h2
      style={styleProps}
      onClick={ () => { context.emit('item-click', { name: 'Title', props: { ...mergeProps } }) } }>
      {props.text}
    </h2>
  )
}

export default Title

// src/components/Title.vue
<template>
  <h2 :style="styleProps">
    {{text}}
  </h2>
</template>
<script lang="ts">
import { pick } from 'lodash'
import { defineComponent, computed } from 'vue'

// Props in component validation
export const TitleProps = {
  text: {
    type: String,
    default: 'Hello World'
  },
  fontSize: {
    type: String,
    default: '30px'
  }
}
export const defaultProps = {
  text: 'Hello World',
  fontSize: '30px'
}
// array that contains style props
export const stylePropsArr = ['fontSize']

export default defineComponent({
  props: TitleProps,
  setup (props) {
    const styleProps = computed(() => pick(props, stylePropsArr))
    return {
      styleProps
    }
  }
})
</script>
